spring:
  datasource:
    url: jdbc:h2:mem:todoapp
    driverClassName: org.h2.Driver
    username: sa
    password: password  # note, would normally set this as an environment variable for the user, or inject as a secret
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true